### PR TITLE
[CORE-2698] fixing logging after istio was introduced

### PR DESCRIPTION
**Pull request by sorenmat**
When istio was introduced we are running more containers in the same pod. So we need to select one, we are now getting logs from the 'main' container which is the application itself.
Also wrote 'system' errors back to the user like this:
image

### CODE REVIEW

**Review by hofmeister — APPROVED** [review]
Nice - what if there are multiple pods ?

**Comment by sorenmat** [comment]
We are only getting the logs from one pod at the time, so it shouldn't be a problem

**Comment by hofmeister** [comment]
The ui doesnt support that yet?

**Comment by sorenmat** [comment]
not what I know of??

**Pull request merged**
